name: beima
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  # For SVG image
  flutter_svg:

  # For connectivity
  connectivity_plus: ^2.3.6+1

  # For state management
  flutter_bloc: ^8.0.1

  # For dependencies
  get_it: ^7.2.0

  # For smooth page transition
  page_transition: ^2.0.5

  # For international phone number
  intl_phone_number_input: ^0.7.0+2

  # For Toast messages
  fluttertoast: ^8.0.8

  # shimmer effect
  fade_shimmer: ^2.0.1

  # For internet connections
  http: ^0.13.4

  # For launcher icon
  flutter_launcher_icons: "^0.9.2"

  # For splashscreen:
  flutter_native_splash:

  # Fade in animations
  flutter_fadein: ^2.0.0

  # Google fonts
  google_fonts:

  # Internationalization, numbers etc
  intl: ^0.17.0

  # Load and Catch Image
  cached_network_image: ^3.2.0

  # Local DB
  shared_preferences: ^2.0.13

  # URL launcher
  url_launcher: ^6.1.5

  # URL launcher
  open_mail_app: ^0.4.5

  # Paystack
  flutter_paystack:
    git:
      url: https://github.com/definitelyme/flutter_paystack.git
      ref: a4a33c3dd0a12f46d655a2e63d11e9f20ba82d01

  # Change package name
  change_app_package_name: ^1.1.0

flutter_icons:
  ios: true
  image_path: assets/icon.png

flutter_native_splash:
  color: "#000000"
  image: assets/logo.png
  android: true
  ios: true

dev_dependencies:
  flutter_test:
    sdk: flutter

  
  flutter_lints: ^1.0.0


flutter:

  uses-material-design: true

  assets:
    - assets/

  fonts:
    - family: Freizeit
      fonts:
        - asset: assets/font/freizeit.ttf
  
  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
